{
 "title": "03. MinIO Distributed Comprehensive Monitoring",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(minio_cluster_health_status,instance)"
    }
   },
   {
    "name": "drive",
    "label": "Drive",
    "query": {
     "query": "label_values(minio_node_drive_free_bytes{instance=\"$node\"},drive)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(minio_bucket_usage_total_bytes{instance=~\"$node\"},bucket)"
    }
   },
   {
    "name": "rate_interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Health Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "minio_cluster_health_status", "legendFormat": "Pool: {{pool}} Set: {{set}}" }
     ]
    },
    {
     "title": "Total Online/Offline Nodes",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(minio_cluster_nodes_online_total{instance=~\"$node\"})"
      },
      {
       "expr": "max(minio_cluster_nodes_offline_total{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Number of Buckets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "minio_cluster_bucket_total" }
     ]
    },
    {
     "title": "Total S3 Ingress",
     "type": "stat",
     "description": "Tổng số byte dữ liệu mà mỗi node MinIO nhận được qua các API request. Giúp theo dõi lưu lượng inbound và phát hiện node chịu tải cao.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_received_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Usable Capacity",
     "type": "piechart",
     "description": "Dung lượng đã sử dụng trên node MinIO có tổng dung lượng usable lớn nhất trong cluster. Giúp phát hiện node chịu tải lưu trữ cao nhất và đánh giá cân bằng dữ liệu trong cluster.",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{instance=~\"$node\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{instance=~\"$node\"}) by (instance))",
       "legendFormat": "Used"
      },
      {
       "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{instance=~\"$node\"}) by (instance)) ",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Raw Capacity",
     "type": "piechart",
     "description": "Dung lượng đã sử dụng trên node MinIO có tổng dung lượng usable lớn nhất trong cluster. Giúp phát hiện node chịu tải lưu trữ cao nhất và đánh giá cân bằng dữ liệu trong cluster.",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1, sum(minio_cluster_capacity_raw_total_bytes{instance=~\"$node\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_raw_free_bytes{instance=~\"$node\"}) by (instance))",
       "legendFormat": "Used"
      },
      {
       "expr": "topk(1, sum(minio_cluster_capacity_raw_free_bytes{instance=~\"$node\"}) by (instance))",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Total Online/Offline Erasure Sets",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(minio_cluster_health_erasure_set_status == 1)"
      },
      {
       "expr": "count(minio_cluster_health_erasure_set_status) - count(minio_cluster_health_erasure_set_status == 1)"
      }
     ]
    },
    {
     "title": "Time Since Last Scan",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minio_usage_last_activity_nano_seconds{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Number of Objects",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_usage_object_total"
      }
     ]
    },
    {
     "title": "Total S3 Egress",
     "type": "stat",
     "description": "Tổng số byte dữ liệu mà mỗi node MinIO gửi đi qua các API request, giúp theo dõi lưu lượng outbound và nhận biết node chịu tải cao.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Total Online/Offline Drives",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_drive_online_total"
      },
      {
       "expr": "minio_cluster_drive_total - minio_cluster_drive_online_total"
      }
     ]
    },
    {
     "title": "Read Quorum",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_read_quorum",
       "legendFormat": "RQ - Pool: {{pool}} - Set: {{set}}"
      }
     ]
    },
    {
     "title": "Write Quorum",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      },
      {
       "expr": "minio_cluster_health_erasure_set_write_quorum",
       "legendFormat": "WQ - Pool: {{pool}} - Set: {{set}}"
      }
     ]
    },
    {
     "title": "Erasure Set Health Status",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_status",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      }
     ]
    },
    {
     "title": "Erasure Set – Healing Drives",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_healing_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      }
     ]
    },
    {
     "title": "Erasure Set – Online Drives",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      },
      {
       "expr": "minio_cluster_health_erasure_set_online_drives",
       "legendFormat": " Pool: {{pool}} - Set: {{set}} "
      }
     ]
    },
    {
     "title": "Object Size Distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_objects_size_distribution",
       "legendFormat": "{{range}}"
      }
     ]
    },
    {
     "title": "Data Usage Growth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "minio_cluster_usage_total_bytes",
       "legendFormat": "Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributed Node Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Overview",
     "type": "table",
     "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "time() - max(minio_node_process_starttime_seconds{instance=~\"$node\"})",
       "legendFormat": "Uptime"
      },
      {
       "expr": "sum(minio_node_drive_online_total) by(instance)",
       "legendFormat": "Online Drives"
      },
      {
       "expr": "sum(minio_node_drive_offline_total) by(instance)",
       "legendFormat": "Offline Drives"
      },
      {
       "expr": "sum by (instance) (increase(minio_heal_objects_errors_total[$rate_interval])) or vector(0)",
       "legendFormat": "Healing Errors"
      },
      {
       "expr": "sum by (instance) (minio_node_file_descriptor_open_total / minio_node_file_descriptor_limit_total) * 100",
       "legendFormat": "File Descriptors %"
      },
      {
       "expr": "sum by (instance) (minio_node_go_routine_total)",
       "legendFormat": "Go Routines"
      },
      {
       "expr": "sum by (instance) (irate(minio_node_io_read_bytes{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "Disk Read*"
      },
      {
       "expr": "sum by (instance) (irate(minio_node_io_write_bytes{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "Disk Write*"
      },
      {
       "expr": "(\r\n  sum by (instance) (minio_node_process_resident_memory_bytes{instance=~\"$node\"})\r\n  / \r\n  sum by (instance) (minio_node_mem_total{instance=~\"$node\"})\r\n) * 100",
       "legendFormat": "Memory Usage %"
      },
      {
       "expr": "sum by (instance) (rate(minio_node_process_cpu_total_seconds{instance=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "CPU Usage %"
      },
      {
       "expr": "(sum by (instance) (minio_node_drive_used_bytes{instance=~\"$node\"}) / \r\n sum by (instance) (minio_node_drive_total_bytes{instance=~\"$node\"})) * 100",
       "legendFormat": "Disk Usage %"
      },
      {
       "expr": "(sum by (instance) (minio_node_drive_used_inodes{instance=~\"$node\"}) / \r\n sum by (instance) (minio_node_drive_total_inodes{instance=~\"$node\"})) * 100",
       "legendFormat": "Inode Usage %"
      },
      {
       "expr": "sum by (instance,version) (minio_software_version_info{instance=~\"$node\"})",
       "legendFormat": "MinIO Release"
      }
     ]
    },
    {
     "title": "Open FDs ",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "minio_node_file_descriptor_open_total{instance=~\"$node\"}",
       "legendFormat": "Open File"
      },
      {
       "expr": "minio_node_file_descriptor_limit_total{instance=~\"$node\"}",
       "legendFormat": "Limit File"
      }
     ]
    },
    {
     "title": "Memory - CPU MinIO",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 3, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_node_process_resident_memory_bytes{instance=~\"$node\"})",
       "legendFormat": "RSS Memory"
      },
      {
       "expr": "rate(minio_node_process_cpu_total_seconds{instance=~\"$node\"}[$rate_interval])",
       "legendFormat": "CPU Cores"
      }
     ]
    },
    {
     "title": "Disk Usage per Drive",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(minio_node_drive_used_bytes{instance=~\"$node\", drive=~\"$drive.*\"} / minio_node_drive_total_bytes{instance=~\"$node\", drive=~\"$drive.*\"}) * 100",
       "legendFormat": "{{instance}} - {{drive}}"
      }
     ]
    },
    {
     "title": "Disk Utilization per Drive",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_node_drive_perc_util{instance=~\"$node\", drive=~\"$drive.*\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Inodes Usage per Drive",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(minio_node_drive_used_inodes{instance=~\"$node\", drive=~\"$drive.*\"} / minio_node_drive_total_inodes{instance=~\"$node\", drive=~\"$drive.*\"}) * 100",
       "legendFormat": "{{instance}} - {{drive}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "minio_node_go_routine_total{instance=~\"$node\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Drive Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(minio_node_drive_errors_availability{instance=~\"$node\", drive=~\"$drive.*\"}[$rate_interval])) by (instance,drive)",
       "legendFormat": "{{instance}} - {{drive}}"
      }
     ]
    },
    {
     "title": "Drive Health: I/O vs Timeout Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(minio_node_drive_errors_ioerror{instance=~\"$node\", drive=~\"$drive.*\"}[$rate_interval])) by (instance,drive)",
       "legendFormat": "{{instance}} - {{drive}}"
      },
      {
       "expr": "sum(increase(minio_node_drive_errors_timeout{instance=~\"$node\", drive=~\"$drive.*\"}[$rate_interval])) by (instance,drive)",
       "legendFormat": "{{instance}} - {{drive}}"
      }
     ]
    },
    {
     "title": "Disk Latency (Await) - Read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "minio_node_drive_reads_await{instance=~\"$node\", drive=~\"$drive.*\"}",
       "legendFormat": "{{instance}} - {{drive}}"
      }
     ]
    },
    {
     "title": "Disk Latency (Await) - Write",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "minio_node_drive_writes_await{instance=~\"$node\", drive=~\"$drive.*\"}",
       "legendFormat": "{{instance}} - {{drive}}"
      }
     ]
    },
    {
     "title": "Disk I/O API Latency (µs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "minio_node_drive_latency_us{instance=~\"$node\", drive=~\"$drive.*\"}",
       "legendFormat": "drive: {{drive}} - {{api}}"
      }
     ]
    },
    {
     "title": "I/O Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(minio_node_drive_io_waiting{instance=~\"$node\", drive=~\"$drive.*\"}[$rate_interval])) by (instance, drive)",
       "legendFormat": "{{instance}} - {{drive}}"
      }
     ]
    },
    {
     "title": "Bucket Scans Started",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minio_node_scanner_bucket_scans_started{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bucket Scans Finished",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(minio_node_scanner_bucket_scans_finished{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drive Throughput, IOPS & Syscalls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Throughput (Read vs Write KB/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "minio_node_drive_reads_kb_per_sec{instance=\"$node\", drive=~\"$drive\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "- minio_node_drive_writes_kb_per_sec{instance=\"$node\", drive=~\"$drive\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Disk IOPS (Operations per Second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "minio_node_drive_reads_per_sec{instance=\"$node\", drive=~\"$drive\"}",
       "legendFormat": "Read IOPS"
      },
      {
       "expr": "minio_node_drive_writes_per_sec{instance=\"$node\", drive=~\"$drive\"}",
       "legendFormat": "Write IOPS"
      }
     ]
    },
    {
     "title": "Logical Disk Throughput (App Level)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(minio_node_io_rchar_bytes{instance=~\"$node\"}[$rate_interval])",
       "legendFormat": "Logical Read"
      },
      {
       "expr": "rate(minio_node_io_wchar_bytes{instance=~\"$node\"}[$rate_interval])",
       "legendFormat": "Logical Write"
      }
     ]
    },
    {
     "title": "Actual Disk I/O (Physical)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(minio_node_io_read_bytes{instance=~\"$node\"}[$rate_interval])",
       "legendFormat": "Disk Read (Physical)"
      },
      {
       "expr": "rate(minio_node_io_write_bytes{instance=~\"$node\"}[$rate_interval])",
       "legendFormat": "Disk Write (Physical)"
      }
     ]
    },
    {
     "title": "Process Syscalls Rate (Read/Write)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(minio_node_syscall_read_total{instance=~\"$node\"}[$rate_interval])",
       "legendFormat": "SysCalls - Read"
      },
      {
       "expr": "rate(minio_node_syscall_write_total{instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "SysCalls - Write"
      }
     ]
    }
   ]
  },
  {
   "title": "Bucket Specific Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Data Stored (Logical) - Bucket: $bucket",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_bucket_usage_total_bytes{instance=~\"$node\", bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "Number of Objects - Bucket: $bucket - Time Series",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 5, "y": 4 },
     "targets": [
      {
       "expr": "minio_bucket_usage_object_total{instance=~\"$node\", bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "Total Data Stored (Logical) - Bucket: $bucket - Time Series",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 4 },
     "targets": [
      {
       "expr": "minio_bucket_usage_total_bytes{instance=~\"$node\", bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "Number of Objects - Bucket: $bucket",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_bucket_usage_object_total{instance=~\"$node\", bucket=~\"$bucket\"}"
      }
     ]
    },
    {
     "title": "Total Data Received Rate - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(minio_bucket_traffic_received_bytes{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Data Sent Rate - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(minio_bucket_traffic_sent_bytes{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Object Size Distribution - Bucket: $bucket",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_bucket_objects_size_distribution{instance=~\"$node\",bucket=~\"$bucket\"}",
       "legendFormat": "{{range}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster API Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 API Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_total{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Canceled",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_canceled_total{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Error Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_errors_total{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Error Rate (Auth Failure)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_rejected_auth_total{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "Rejected Auth"
      },
      {
       "expr": "sum by (instance,api) (increase(minio_s3_requests_rejected_header_total{instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "Rejected Header"
      },
      {
       "expr": "sum by (instance,api) (increase(minio_s3_requests_rejected_invalid_total{instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "Rejected Invalid"
      },
      {
       "expr": "sum by (instance,api) (increase(minio_s3_requests_rejected_timestamp_total{instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "Rejected Timestamp"
      }
     ]
    },
    {
     "title": "S3 API Request Error Rate (4xx)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_4xx_errors_total{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Error Rate (5xx)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_5xx_errors_total{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request InFlight",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (api) (minio_s3_requests_inflight_total{instance=~\"$node\"})",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Waiting",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (api) (minio_s3_requests_waiting_total{instance=~\"$node\"})",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "S3 API Ingress Rate ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(minio_s3_traffic_received_bytes{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "Data Received [{{server}}]"
      }
     ]
    },
    {
     "title": "S3 API Egress Rate ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(minio_s3_traffic_sent_bytes{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "Data Sent {{instance}}"
      }
     ]
    },
    {
     "title": "API TTFB – P95",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (api, le) (\r\n    rate(minio_s3_requests_ttfb_seconds_distribution[$rate_interval])\r\n  )\r\n)",
       "legendFormat": "histogram_quantile_95%_api: {{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-Bucket API Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 API Request Rate - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_bucket_requests_total{instance=~\"$node\", bucket=~\"$bucket\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Canceled - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_bucket_requests_canceled_total{instance=~\"$node\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Error Rate (4xx) - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_bucket_requests_4xx_errors_total{instance=~\"$node\", bucket=~\"$bucket\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request Error Rate (5xx) - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_bucket_requests_5xx_errors_total{instance=~\"$node\",bucket=~\"$bucket\"}[$rate_interval]))",
       "legendFormat": "{{server}} - {{api}}"
      }
     ]
    },
    {
     "title": "S3 API Request InFlight - Bucket: $bucket",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (server, api) (minio_bucket_requests_inflight_total{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "{{api}}"
      }
     ]
    },
    {
     "title": "S3 API Ingress Rate - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(minio_bucket_traffic_received_bytes{instance=~\"$node\", bucket=~\"$bucket\"}[$rate_interval]))",
       "legendFormat": "Data Received [{{server}}]"
      }
     ]
    },
    {
     "title": "S3 API Egress Rate - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(minio_bucket_traffic_sent_bytes{instance=~\"$node\", bucket=~\"$bucket\"}[$rate_interval]))",
       "legendFormat": "Data Sent {{instance}}"
      }
     ]
    },
    {
     "title": "API TTFB – P95 - Bucket: $bucket",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (api, le) (\r\n    rate(minio_bucket_requests_ttfb_seconds_distribution{bucket=~\"$bucket\"}[$rate_interval])\r\n  )\r\n)",
       "legendFormat": "histogram_quantile_95%_api: {{api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Active Workers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_average_active_workers{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Current Active Workers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_current_active_workers{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Max Active Workers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "minio_node_replication_max_active_workers{instance=~\"$node\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Avg. Link Latency (millis)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (server, endpoint) (minio_node_replication_average_link_latency_ms{instance=~\"$node\"})",
       "legendFormat": "{{server,endpoint}}"
      }
     ]
    },
    {
     "title": "Current Link Latency (millis)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,endpoint) (minio_node_replication_current_link_latency_ms{instance=~\"$node\"})",
       "legendFormat": "{{server,endpoint}}"
      }
     ]
    },
    {
     "title": "Max Link Latency (millis)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,endpoint) (minio_node_replication_max_link_latency_ms{instance=~\"$node\"})",
       "legendFormat": "{{server,endpoint}}"
      }
     ]
    },
    {
     "title": "Avg. Queued Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_average_queued_bytes{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Last Minute Queued Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_last_minute_queued_bytes{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Max Queued Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_max_queued_bytes{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Avg. Queued Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_average_queued_count{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Last Minute Queued Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_last_minute_queued_count{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Max Queued Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "minio_node_replication_max_queued_count{instance=~\"$node\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Avg. Transfer Rate (bytes/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_average_transfer_rate{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Current Transfer Rate (bytes/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (server) (minio_node_replication_current_transfer_rate{instance=~\"$node\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Max Transfer Rate (per sec)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "minio_node_replication_max_transfer_rate{instance=~\"$node\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Link Downtime Duration (sec)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,endpoint) (minio_node_replication_link_downtime_duration_seconds{instance=~\"$node\"})",
       "legendFormat": "{{server,endpoint}}"
      }
     ]
    },
    {
     "title": "Link Offline Duration (sec)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,endpoint) (minio_node_replication_link_offline_duration_seconds{instance=~\"$node\"})",
       "legendFormat": "{{server,endpoint}}"
      }
     ]
    },
    {
     "title": "Link Online/Offline",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,endpoint) (minio_node_replication_link_online{instance=~\"$node\"})",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Replication Link Offline Duration (sec)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "minio_node_replication_link_offline_duration_seconds{instance=~\"$node\"}",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bucket Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Data Received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_received_bytes{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "Data Received [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replication Data Sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_sent_bytes{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "Replication Data Sent [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replication Data Failed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_total_failed_bytes{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "Replication Failed [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replication Failed Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_total_failed_count{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "Replication Failed Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replicated In Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_received_count{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "Replicated In Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replicated Out Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_sent_count{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "Replicated Out Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Last Hour Failed Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(minio_bucket_replication_last_hour_failed_bytes{instance=~\"$node\", bucket=~\"$bucket\"}[$rate_interval]))",
       "legendFormat": "Last Hour Failed Size [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Last Hour Failed Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_last_hour_failed_count{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "Last Hour Failed Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Last Minute Failed Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (bucket) (rate(minio_bucket_replication_last_minute_failed_bytes{instance=~\"$node\", bucket=~\"$bucket\"}[$rate_interval]))",
       "legendFormat": "Last Minute Failed Size [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Last Minute Failed Objects",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bucket) (minio_bucket_replication_last_minute_failed_count{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "Last Minute Failed Objects [{{bucket}}]"
      }
     ]
    },
    {
     "title": "Replication Latency (millis)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (bucket,range,operation) (minio_bucket_replication_latency_ms{instance=~\"$node\", bucket=~\"$bucket\"})",
       "legendFormat": "{{bucket,range,operation}}"
      }
     ]
    }
   ]
  }
 ]
}