import os
from datetime import datetime
from typing import Any

from airflow import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from airflow.providers.standard.operators.python import PythonOperator

from _spark_common import (
    iceberg_dataset,
    iceberg_maintenance,
    spark_base_conf,
    spark_env_vars,
    spark_job_base,
    spark_packages,
    spark_utils_py_files,
)


# ===== DEFAULT AIRFLOW SETTINGS =====
# - owner: team that owns this DAG
# - depends_on_past: False — each run is independent of prior runs
# - retries: 0 — no retry on failure (streaming jobs are expected to be long-running)
default_args = {"owner": "DataForge", "depends_on_past": False, "retries": 0}

# ===== SPARK CONFIGURATION =====
# Loaded from _spark_common module (Hive Metastore, Iceberg catalog, MinIO/S3, Kafka)
PACKAGES = spark_packages()
BASE_CONF = spark_base_conf()
ENV_VARS = spark_env_vars()

# ===== SPARK JOB APPLICATIONS =====
# Paths to Spark job Python scripts mounted inside the container
SPARK_JOB_BASE = spark_job_base()

# Script for multi-topic aggregation (raw_events):
# Consumes multiple Kafka topics, applies Avro deserialization, writes to Iceberg.
AGG_APPLICATION = os.path.join(SPARK_JOB_BASE, "bronze_events_kafka_stream.py")

# Script for single-topic CDC processing:
# Consumes Debezium CDC messages, applies INSERT/UPDATE/DELETE semantics, writes to Iceberg.
TOPIC_APPLICATION = os.path.join(SPARK_JOB_BASE, "bronze_cdc_stream.py")

# Python files distributed to Spark executors alongside the job
SPARK_PY_FILES = spark_utils_py_files()

# ===== DEFAULT STREAM CONFIGURATION =====
# Baseline values for stream parameters (overridden per-stream as needed)
DEFAULT_CONFIG = {
    # Records per micro-batch — larger batch = fewer commits but higher end-to-end latency
    "batch_size": 5000,
    # "earliest" = replay from offset 0; "latest" = only consume messages arriving after startup
    "starting_offsets": "earliest",
    # Delete Iceberg snapshots older than this threshold
    "expire_days": "7d",
}

# ===== BRONZE STREAMS CONFIGURATION =====
# Defines all streams that ingest data into the Bronze layer.
# Key: stream identifier; Value: stream configuration dict
BRONZE_STREAMS = {
    # ===== AGGREGATED EVENTS (multiple topics merged into one table) =====
    "raw_events": {
        # type: "multi_topic" = merge multiple Kafka topics into one shared Bronze table
        "type": "multi_topic",
        # Kafka topics to consume — generated by the demo event generator
        "topics": [
            "orders.v1",                   # Order events
            "payments.v1",                 # Payment events
            "shipments.v1",                # Shipment events
            "inventory-changes.v1",        # Inventory change events
            "customer-interactions.v1",    # Customer interaction events
        ],
        # Target Iceberg table where all merged events are stored
        "table": "iceberg.bronze.raw_events",
        # Streaming checkpoint directory on S3 (persists offset state between runs)
        "checkpoint": "s3a://checkpoints/spark/iceberg/bronze/raw_events",
        # Spark job script that handles multi-topic aggregation
        "application": AGG_APPLICATION,
        # Events per micro-batch — higher limit for raw_events due to large volume
        "batch_size": 50000,
        # Only consume new messages from this point forward (do not replay history)
        "starting_offsets": "latest",
        "expire_days": "7d",
    },
    
    # ===== CDC TOPICS (Debezium from PostgreSQL) =====
    # Each CDC topic is mapped 1:1 to a dedicated Bronze table
    
    "cdc_users": {
        "type": "single_topic",
        "name": "users",
        # Debezium topic from the PostgreSQL 'public.users' table
        "topic": "demo.public.users",
        # Target Bronze table— 1:1 mapping from the source table
        "table": "iceberg.bronze.demo_public_users",
        # Checkpoint path — must be unique per stream
        "checkpoint": "s3a://checkpoints/spark/iceberg/bronze/cdc/demo_public_users",
        # Spark job script for CDC processing (handles INSERT / UPDATE / DELETE)
        "application": TOPIC_APPLICATION,
    },
    
    "cdc_products": {
        "type": "single_topic",
        "name": "products",
        "topic": "demo.public.products",
        "table": "iceberg.bronze.demo_public_products",
        "checkpoint": "s3a://checkpoints/spark/iceberg/bronze/cdc/demo_public_products",
        "application": TOPIC_APPLICATION,
    },
    
    "cdc_inventory": {
        "type": "single_topic",
        "name": "inventory",
        "topic": "demo.public.inventory",
        "table": "iceberg.bronze.demo_public_inventory",
        "checkpoint": "s3a://checkpoints/spark/iceberg/bronze/cdc/demo_public_inventory",
        "application": TOPIC_APPLICATION,
    },
    
    "cdc_warehouse_inventory": {
        "type": "single_topic",
        "name": "warehouse_inventory",
        "topic": "demo.public.warehouse_inventory",
        "table": "iceberg.bronze.demo_public_warehouse_inventory",
        "checkpoint": "s3a://checkpoints/spark/iceberg/bronze/cdc/demo_public_warehouse_inventory",
        "application": TOPIC_APPLICATION,
    },
    
    "cdc_suppliers": {
        "type": "single_topic",
        "name": "suppliers",
        "topic": "demo.public.suppliers",
        "table": "iceberg.bronze.demo_public_suppliers",
        "checkpoint": "s3a://checkpoints/spark/iceberg/bronze/cdc/demo_public_suppliers",
        "application": TOPIC_APPLICATION,
    },
    
    "cdc_customer_segments": {
        "type": "single_topic",
        "name": "customer_segments",
        "topic": "demo.public.customer_segments",
        "table": "iceberg.bronze.demo_public_customer_segments",
        "checkpoint": "s3a://checkpoints/spark/iceberg/bronze/cdc/demo_public_customer_segments",
        "application": TOPIC_APPLICATION,
    },
    
    "cdc_warehouses": {
        "type": "single_topic",
        "name": "warehouses",
        "topic": "demo.public.warehouses",
        "table": "iceberg.bronze.demo_public_warehouses",
        "checkpoint": "s3a://checkpoints/spark/iceberg/bronze/cdc/demo_public_warehouses",
        "application": TOPIC_APPLICATION,
    },
}


# ===== HELPER FUNCTION =====
def build_default_params(streams: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """
    Build the default params dict for the DAG from BRONZE_STREAMS configuration.

    Constructs an Airflow params dictionary that allows per-run overrides of
    stream settings when the DAG is triggered manually.

    Args:
        streams: BRONZE_STREAMS configuration dictionary.

    Returns:
        dict: Default params containing stream settings in an overrideable format:
              - streams: mapping of stream identifier -> config
              - top-level keys: batch_size, table, checkpoint, etc. from raw_events
    """
    defaults: dict[str, Any] = {"streams": {}}

    for key, conf in streams.items():
        stream_defaults: dict[str, Any] = {
            "table": conf["table"],
            "checkpoint": conf["checkpoint"],
            "batch_size": conf.get("batch_size", DEFAULT_CONFIG["batch_size"]),
            "starting_offsets": conf.get("starting_offsets", DEFAULT_CONFIG["starting_offsets"]),
            "expire_days": conf.get("expire_days", DEFAULT_CONFIG["expire_days"]),
        }

        if conf["type"] == "multi_topic":
            # Multi-topic: expose the topic list for Jinja templating
            stream_defaults["topics"] = list(conf.get("topics", []))
        elif conf["type"] == "single_topic":
            stream_defaults["topic"] = conf["topic"]
        else:
            raise ValueError(f"Unsupported stream type for defaults: {conf['type']}")

        defaults["streams"][key] = stream_defaults
    
    # Promote raw_events keys to the top level (used as the primary runtime override)
    defaults.update(defaults["streams"]["raw_events"])
    return defaults


# Build default params from the stream registry
DEFAULT_PARAMS = build_default_params(BRONZE_STREAMS)


# ===== TASK FACTORY FUNCTION =====
def create_stream_tasks(stream_key, stream_config, dag):
    """
    Factory that creates an (ingest_task, maintenance_task) pair for one stream.

    ingest_task:       SparkSubmitOperator that runs the Spark streaming job.
    maintenance_task:  PythonOperator that runs Iceberg maintenance after ingestion.

    Args:
        stream_key:    Stream identifier (e.g. "raw_events", "cdc_users").
        stream_config: Stream configuration dict from BRONZE_STREAMS.
        dag:           Airflow DAG instance.

    Returns:
        tuple: (ingest_task, maintenance_task)
    """
    # Merge DEFAULT_CONFIG with stream-specific config (stream values win)
    config = {**DEFAULT_CONFIG, **stream_config}
    
    # ===== MULTI-TOPIC AGGREGATION =====
    if config["type"] == "multi_topic":
        task_id = "bounded_ingest"
        maintenance_task_id = "iceberg_maintenance_bronze_raw_events"
        
        # Application args use Jinja templating for runtime flexibility:
        # {{ dag_run.conf.* }} = override from the DAG trigger config
        # {{ params.* }}       = fallback to the default params
        # | join(',')          = convert a list to a comma-separated string
        application_args = [
            "--topics",
            "{{ (dag_run.conf.topics if dag_run and dag_run.conf and dag_run.conf.topics is not none else params.topics) | join(',') }}",
            "--batch-size", 
            "{{ dag_run.conf.batch_size if dag_run and dag_run.conf and dag_run.conf.batch_size is not none else params.batch_size }}",
            "--checkpoint",
            "{{ dag_run.conf.checkpoint if dag_run and dag_run.conf and dag_run.conf.checkpoint is not none else params.checkpoint }}",
            "--starting-offsets",
            "{{ dag_run.conf.starting_offsets if dag_run and dag_run.conf and dag_run.conf.starting_offsets is not none else params.starting_offsets }}",
            "--table",
            "{{ dag_run.conf.table if dag_run and dag_run.conf and dag_run.conf.table is not none else params.table }}",
        ]
        
        # Jinja templates resolved at runtime for the maintenance task
        table_ref = "{{ dag_run.conf.table if dag_run and dag_run.conf and dag_run.conf.table is not none else params.table }}"
        expire_days_ref = "{{ dag_run.conf.expire_days if dag_run and dag_run.conf and dag_run.conf.expire_days is not none else params.expire_days }}"
        
    # ===== SINGLE-TOPIC CDC STREAMS =====
    elif config["type"] == "single_topic":
        # Separate task per CDC topic
        name = config["name"]
        task_id = f"ingest_{name}"
        maintenance_task_id = f"iceberg_maintenance_{name}"
        
        # Simple application arguments - không có template vì values fixed
        application_args = [
            "--topic", config["topic"],  # Kafka topic name
            "--table", config["table"],  # Target Iceberg table
            "--checkpoint", config["checkpoint"],  # Checkpoint dir
            "--batch-size", str(config["batch_size"]),  # Events per micro-batch
            "--starting-offsets", config["starting_offsets"],  # "earliest" or "latest"
        ]
        
        # Literal references (không template) vì values fixed
        table_ref = config["table"]
        expire_days_ref = config["expire_days"]
        
    else:
        raise ValueError(f"Unknown stream type: {config['type']}")
    
    # ===== INGEST TASK =====
    ingest_task = SparkSubmitOperator(
        task_id=task_id,
        conn_id="spark_default",      # Airflow connection pointing to Spark
        application=config["application"],  # bronze_events_kafka_stream.py or bronze_cdc_stream.py
        py_files=SPARK_PY_FILES,     # spark_utils.py distributed to executors
        packages=PACKAGES,           # Maven coordinates (Kafka, Iceberg, Hadoop, AWS)
        env_vars=ENV_VARS,           # AWS credentials and paths
        conf=BASE_CONF,              # Spark config (Hive, Iceberg, MinIO, Kafka)
        application_args=application_args,
        verbose=True,
        # Mark the target table as produced once the ingest task completes
        outlets=[iceberg_dataset(config["table"])],
        dag=dag,
    )
    
    # ===== MAINTENANCE TASK =====
    maintenance_task = PythonOperator(
        task_id=maintenance_task_id,
        python_callable=iceberg_maintenance,
        op_kwargs={
            "table": table_ref,          # Table name (may be a Jinja template)
            "expire_days": expire_days_ref,  # Snapshot retention (may be a template)
        },
        dag=dag,
    )
    
    # Ingest must complete before maintenance runs
    ingest_task >> maintenance_task
    
    return ingest_task, maintenance_task


# ===== AIRFLOW DAG DEFINITION =====
# DAG that orchestrates Kafka → Bronze ingestion pipelines
with DAG(
    dag_id="bronze_events_kafka_stream",
    description="Ingest Kafka demo streams and Debezium CDC topics into Bronze",
    doc_md="""\
        #### Bronze Layer Kafka Ingestion

        Ingests real-time data from Kafka into Bronze Iceberg tables.

        **Two source types**:
        1. **Aggregated Events** (`raw_events`):
           - Merges 5 demo topics into one shared Bronze table.
           - Topics: orders, payments, shipments, inventory-changes, customer-interactions.

        2. **CDC Streams** (7 Debezium topics):
           - Each Debezium topic is mapped 1:1 to its own Bronze table.
           - Sources: users, products, inventory, warehouse_inventory, suppliers,
             customer_segments, warehouses.
           - CDC = Change Data Capture — tracks INSERT/UPDATE/DELETE from PostgreSQL.

        **Processing pipeline**:
        - Spark Structured Streaming consumes from Kafka.
        - Avro messages are decoded via the Schema Registry.
        - CDC streams apply UPSERT semantics; event streams append.
        - Each run is followed by Iceberg maintenance (OPTIMIZE, EXPIRE_SNAPSHOTS, REMOVE_ORPHANS).

        **Checkpoint management**:
        - Each stream has its own S3 checkpoint directory.
        - Spark persists consumer offsets and execution state.
        - Failed tasks resume from the last committed offset.
        """,
    start_date=None,
    max_active_tasks=2,
    schedule=None,    # Triggered manually or by an external system
    catchup=False,
    default_args=default_args,
    params=DEFAULT_PARAMS,
    tags=["streaming", "cdc", "iceberg"],
) as dag:
    # Create an (ingest, maintenance) task pair for every registered stream
    for stream_key, stream_config in BRONZE_STREAMS.items():
        create_stream_tasks(stream_key, stream_config, dag)
